### ISSUE TITLE
xtoken uses its own ProxyAdmin and Low Messager.

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/xtoken-monorepo#37]
ProxyAdmin
Darwinia: 0xCfff66D03Ad2634d224b76967051Fa7B33fd0665
Ethereum: 0x44fE8409043F10c63B2b5B484774b1Cef122Cc32

Messager
Darwinia: 0x682294D1c00A9CA13290b53B7544b8F734D6501f
Ethereum: 0x02e5C0a36Fb0C83CCEBCD4D6177A7E223D6f0b7c

Backing(Darwinia)
0x2B496f19A420C02490dB859fefeCCD71eDc2c046
Issuing(Ethereum)
0xDc0C760c0fB4672D06088515F6446a71Df0c64C1

NewOwner: 0x000000000879926D12aF396788C0785B7e581e53

**Comment by hujw77** [comment]
Transfer to RingDAO Sphinx Safe Address https://github.com/darwinia-network/contracts-deploy/blob/29eb12105c653b473014a7bee171e458c9f8dc33/script/x-token/Config.s.sol#L35C1-L36C1

**Comment by xiaoch05** [comment]
resolved
